#!/bin/bash
#SBATCH -o msatr.%j.out
#SBATCH -p gpu31
#SBATCH --qos=normal
#SBATCH -J msatr
#SBATCH --nodes=1 
#SBATCH --gres=gpu:1
#SBATCH -t 120:00:00

msa=contact7.5_kmeans32_mmseqs2_1024/EX.a3m
python ../../runESM.py  $msa \
-o  msatr/mmseqs2_1024/

