#!/bin/bash
#SBATCH -o af2.%j.out
#SBATCH -p gpu31
#SBATCH --qos=normal
#SBATCH -J af2
#SBATCH --nodes=1 
#SBATCH --gres=gpu:1
#SBATCH -t 120:00:00

gts=`ls gt_structures/*`
gt1=`echo $gts | awk '{ print $1 }'`
gt2=`echo $gts | awk '{ print $2 }'`
msas=test.a3m
python ../../runAF2.py $msas \
--output_dir AF2_0/mmseqs2/ \
-gt1 $gt1 \
-gt2 $gt2 \
--recycles 0 \
--model_num 1 2 3 4 5 \
--seed 0 1 \
--relax \
--use_gpu_relax

# msas=contact7.5_kmeans32_mmseqs2_1024/EX.a3m
# python ../../runAF2.py $msas \
# --output_dir AF2_0/mmseqs2_1024/ \
# -gt1 $gt1 \
# -gt2 $gt2 \
# --recycles 0 \
# --model_num 1 2 3 4 5 \
# --seed 0 1 \
# --relax \
# --use_gpu_relax

# msas=`ls contact7.5_kmeans32/AF2/struct_cluster/*a3m`
# python ../../runAF2.py $msas \
# --output_dir contact7.5_kmeans32/AF2/struct_cluster \
# -gt1 $gt1 \
# -gt2 $gt2

# python ../../run_struct_visual.py EX \
# --output_dir AF2/full_msa \
# -gt1 $gt1 \
# -gt2 $gt2
# msas=`ls contact7.5_kmeans32_mmseqs2_1024/unsupervised_cluster_extend/EX*a3m`
# python ../../runAF2.py $msas \
# --output_dir contact7.5_kmeans32_mmseqs2_1024/AF2_0/unsupervised_cluster_extend \
# -gt1 $gt1 \
# -gt2 $gt2 \
# --recycles 0 \
# --model_num 1 2 3 4 5 \
# --seed 0 1 \
# --relax \
# --use_gpu_relax 

# msas=`ls contact7.5_kmeans32_mmseqs2_1024/supervised_cluster_af2_extend/gt*a3m`
# python ../../runAF2.py $msas \
# --output_dir contact7.5_kmeans32_mmseqs2_1024/AF2_0/supervised_cluster_af2_extend \
# -gt1 $gt1 \
# -gt2 $gt2 \
# --recycles 0 \
# --model_num 1 2 3 4 5 \
# --seed 0 1 \
# --relax \
# --use_gpu_relax 

# msas=`ls contact7.5_kmeans32_mmseqs2_512/unsupervised_cluster/*`
# python ../../runAF2.py $msas \
# --output_dir contact7.5_kmeans32_mmseqs2_512/AF2_0/unsupervised_cluster \
# -gt1 $gt1 \
# -gt2 $gt2 \
# --recycles 0 \
# --model_num 1 2 3 4 5 \
# --seed 0 1 \
# --relax \
# --use_gpu_relax 


# if [ -d contact7.5_kmeans32/unsupervised_cluster_extend ]
# then
# msas=`ls contact7.5_kmeans32/unsupervised_cluster_extend/EX*a3m`
# python ../../runAF2.py $msas \
# --output_dir contact7.5_kmeans32/AF2_0/unsupervised_cluster_extend \
# -gt1 $gt1 \
# -gt2 $gt2 \
# --recycles 0 \
# --model_num 1 2 3 4 5 \
# --seed 0 \
# --relax \
# --use_gpu_relax 
# fi

# python ../../run_struct_visual.py \
# --output_dir contact7.5_kmeans32/AF2_0/unsupervised_cluster \
# -gt1 $gt1 \
# -gt2 $gt2
# fi

# if [ -d contact7.5_kmeans32_raw_att_topn_nofilter/unsupervised_cluster ]
# then
# msas=`ls contact7.5_kmeans32_raw_att_topn_nofilter/unsupervised_cluster/*a3m`
# python ../../runAF2.py $msas \
# --output_dir contact7.5_kmeans32_raw_att_topn_nofilter/AF2/unsupervised_cluster \
# -gt1 $gt1 \
# -gt2 $gt2

# python ../../run_struct_visual.py \
# --output_dir contact7.5_kmeans32_raw_att_topn_nofilter/AF2/unsupervised_cluster \
# -gt1 $gt1 \
# -gt2 $gt2
# fi

# if [ -d contact7.5_kmeans32_raw_att_topn/unsupervised_cluster ]
# then
# msas=`ls contact7.5_kmeans32_raw_att_topn/unsupervised_cluster/*a3m`
# python ../../runAF2.py $msas \
# --output_dir contact7.5_kmeans32_raw_att_topn/AF2/unsupervised_cluster \
# -gt1 $gt1 \
# -gt2 $gt2

# python ../../run_struct_visual.py \
# --output_dir contact7.5_kmeans32_raw_att_topn/AF2/unsupervised_cluster \
# -gt1 $gt1 \
# -gt2 $gt2
# fi

# if [ -d contact20_kmeans32_nofilter/supervised_cluster_af2 ]
# then
# msas=`ls contact20_kmeans32_nofilter/supervised_cluster_af2/*a3m`
# python ../../runAF2.py $msas \
# --output_dir contact20_kmeans32_nofilter/AF2/supervised_cluster \
# -gt1 $gt1 \
# -gt2 $gt2

# python ../../run_struct_visual.py \
# --output_dir contact20_kmeans32_nofilter/AF2/supervised_cluster \
# -gt1 $gt1 \
# -gt2 $gt2
# fi