#!/bin/bash
#SBATCH -o evosplit_step.%j.out
#SBATCH -p gpu31,gpu33,gpu35
#SBATCH --qos=normal
#SBATCH -J evosplit
#SBATCH --nodes=1 
#SBATCH --gres=gpu:1
#SBATCH -t 120:00:00

gts=`ls gt_structures/*`
gt1=`echo $gts | awk '{ print $1 }'`
gt2=`echo $gts | awk '{ print $2 }'`

python ../../run_evosplit_step.py  EX \
-i a3m/test.a3m \
-o contact7.5_kmeans32_mmseqs2_1024_step \
-gt1 $gt1 \
-gt2 $gt2 
