#!/bin/bash
#SBATCH -o af2.%j.out
#SBATCH -p gpu31
#SBATCH --qos=normal
#SBATCH -J af2
#SBATCH --nodes=1 
#SBATCH --gres=gpu:1
#SBATCH -t 120:00:00

gts=`ls gt_structures/*`
gt1=`echo $gts | awk '{ print $1 }'`
gt2=`echo $gts | awk '{ print $2 }'`
msas=`ls evosplit_results/unsupervised_cluster*a3m`
python ../../runAF2.py $msas \
--output_dir AF2_results/ \
-gt1 $gt1 \
-gt2 $gt2 \
--recycles 0 \
--model_num 1 2 3 4 5 \
--seed 0 1 \
--relax \
--use_gpu_relax
