#!/bin/bash
#SBATCH -o evosplit.%j.out
#SBATCH -p gpu31
#SBATCH --qos=normal
#SBATCH -J evosplit
#SBATCH --nodes=1 
#SBATCH --gres=gpu:1
#SBATCH -t 120:00:00

gts=`ls gt_structures/*`
gt1=`echo $gts | awk '{ print $1 }'`
gt2=`echo $gts | awk '{ print $2 }'`

python ../../run_evosplit.py  EX \
-i test.a3m \
-o evosplit_results \
-gt1 $gt1 \
-gt2 $gt2 \
