#!/bin/bash
#SBATCH -o MSA_extend.%j.out
#SBATCH -p hygon,cpu1,cpu2,cpu3
#SBATCH --qos=normal
#SBATCH -J msa
#SBATCH --nodes=1 
#SBATCH -n 8
#SBATCH -t 120:00:00

a3m=test.a3m

python ../../run_MSA_extend.py EX -i $a3m \
-o evosplit_results/unsupervised_cluster_extend \
-MSA_cluster_dir evosplit_results/unsupervised_cluster
